name: Search Engine Application

on: [push]

jobs:
  build:

    name: Máquina de busca
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validar arquivos composer.[json|lock]
      run: cd 03-search && composer validate

    - name: Instalar dependências
      run: cd 03-search && composer install --prefer-dist --no-progress --no-suggest

    - name: Testes unitários
      run: cd 03-search && composer run-script test

    - name: Executar pesquia
      run: cd 03-search && php app search "symfony"